apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n5i5k7h32-dotnet-basic
  janus-idp.io/tekton: n5i5k7h32-dotnet-basic
  backstage.io/kubernetes-id: n5i5k7h32-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n5i5k7h32-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
